### PR TITLE
[horizontal-layout] Added custom layout for horizontal list.

### PR DESCRIPTION
**Pull request by rujiali**
Added custom layout. 

To test:

1. Select UI KIT horizontal list with image layout in your display mode
2. Create a view to display the content type using the display mode
3. Set View format to be HTML list
4. Add `list-horizontal` in List class
5. Check the view page following the UI KIT horizontal list style

### CODE REVIEW

**Comment by rujiali** [comment]
@Feng-Shui , ready for review when you have time.

**Comment by Feng-Shui** [comment]
@rujiali yeah I saw this one this morning, will test this tomorrow morning :)

**Comment by Feng-Shui** [comment]
@rujiali I've pushed some changes back for you to take a look at.  I've made the layout expose more of the markup to DS allowing finer grained control over where fields can be placed.

I've also provided generic styling for taxonomy term reference fields across he board - they'll now be displayed inline like the DTA guide - interested in your thoughts on this being a global change.  If we're happy with it as a global change, we might want to make the implementation more generic as the kit implements it within the list style - pinging DTA on this idea at the moment.

Let me know your thoughts on my changes.  I'm happy to implement the rest of the list styles as DS templates this week.

FYI, my issue this morning was that the UI Kit class was `list-horizontal`, you had `horizontal-list` above, have update the above post :) (because apparently I can edit your posts?!?!?!?)

**Comment by rujiali** [comment]
Thanks @Feng-Shui for applying the proper horizontal list layout in the template. I'm happy to have global inline block for the taxonomy term fields. Question, the UI KIT needs the `tag` class in the field div in `footer`. I suppose we won't have the control of the fields in ds template level. Not sure what is best solution for it. But I'm happy to merge the current change to master now.

**Comment by rujiali** [comment]
Just added the `tag` class to `footer`, please regardless the previous comment about the `tag`.

**Comment by Feng-Shui** [comment]
@rujiali I pushed a PR yesterday afternoon that moved the `.tag` styling out of the list style which has been merged into develop.  If you grab the latest UI Kit (on develop) branch, the you shouldn't need the class on the `footer` element.

If you're happy with a global style, then we should move that additional layout out of the list context too.  I'll push that as an additional commit on this branch.

**Comment by Feng-Shui** [comment]
PR was here: https://github.com/AusDTO/gov-au-ui-kit/pull/459

**Comment by rujiali** [comment]
Thanks @Feng-Shui . Sorry I was left behind. I'm happy with the global style. Feel free to move the additional layout out of the list.

**Pull request merged**
