### PR TITLE
apply nav class to sidebars

### PR DESCRIPTION
**Pull request by DJMyles**
Now that we have 2 new sidebar regions the function in template.php needs to be updated so that the styles are inherited.

If you get a chance @Feng-Shui or @rujiali

### CODE REVIEW

**Comment by Feng-Shui** [comment]
I'm not sure we need that code at all anymore... I think we needed that class to position the sidebar left or right.  Now that we're doing that ourselves, I don't think we need that class at all.

**Comment by DJMyles** [comment]
@Feng-Shui without the code the nav doesn't get the style though.

**Comment by Feng-Shui** [comment]
It needs to get a `local-nav` class on the `<nav>` element to get the styling, I'm working on that now on the navigation issue.  That should allow us to remove this - I suspect this will be removed in 2.0.

**Comment by Feng-Shui** [comment]
Closing this one post slack discussion, this has been fixed now in `feature/navigation`!

**Pull request closed without merging**
