### PR TITLE
Form styling, markup tweaks

### PR DESCRIPTION
**Pull request by Feng-Shui**
This branch contains a bunch of styling/markup tweaks as well as the form styling.  Sorry guys, I know there's a bunch of stuff in there :(

### CODE REVIEW

**Comment by Feng-Shui** [comment]
[form_example.zip](https://github.com/govCMS/ui-kit-base-theme/files/715753/form_example.zip)

Here is a sample form that provides all the elements that I styled against.  One enabled, the form is available at `/example-form`

**Comment by Feng-Shui** [comment]
@DJMyles did you say that you'd reviews this one?

**Comment by DJMyles** [comment]
@Feng-Shui yep and looks good. The only enhancement I would suggest is that when an input fails validation, the browser goes to that element, not to top.

**Comment by Feng-Shui** [comment]
Yeah, in order to make that work we'd need to move the form errors to be inline with the form elements.  There's a module to do that, integration would be a new issue.  Let's pick that up as an enhancement down the road.

**Pull request merged**
