### PR TITLE
First take on a maintenance page.

### PR DESCRIPTION
**Pull request by Feng-Shui**
@mgdhs for your review.

screen shot 2017-01-19 at 3 50 12 pm

### CODE REVIEW

**Comment by mgdhs** [comment]
@Feng-Shui see https://github.com/govCMS/ui-kit-base-theme/issues/53

I'm also unsure about the centre aligned header. Maybe do the same as the regular template, where the logo is left and it is all centre aligned?

**Comment by Feng-Shui** [comment]
No objections.  Can update it next week, or you can throw in a PR, should be a 1 line change.

**Comment by DJMyles** [comment]
I've pushed a change that makes the header like the regular template. Is that what you guys wanted?

**Comment by mgdhs** [comment]
@DJMyles it looks good, but I reckon the left of the logo should line up with the left of the content area. I'll let you do this since you know the structure, CSS and wrappers best.

screen shot 2017-01-20 at 12 06 55

This one also depends on https://github.com/govCMS/ui-kit-base-theme/pull/54. A better way to do it so we can keep it moving is to get this merged, then I update the other PR to update this template. That way this one keeps moving.

**Comment by DJMyles** [comment]
@mgdhs I've published some further changes but this is actually really really difficult to do perfectly because the header is so detached from the content area body in terms of how the grid and columns work in general. It is very difficult to style the header so it behaves like the body (so that the header logo left aligns with the content). I've made it as close as possible but have had to hardcode some percentage magic numbers into it. Happy for you to explore further.

**Comment by Feng-Shui** [comment]
@mgdhs new PR #58

**Pull request merged**
