### PR TITLE
Issues with landscape logos and header containers

### PR DESCRIPTION
**Pull request by Feng-Shui**
#67

### CODE REVIEW

**Comment by Feng-Shui** [comment]
As this uses flexbox, we're going to need to look at this from a supported browser perspective.  @mgdhs can you help test this?

**Comment by Feng-Shui** [comment]
@rujiali this might cause issues with your sub-themes, can you please have a look at this branch too when you get a moment.

**Comment by Feng-Shui** [comment]
This branch needs to be updated to use:

```
    @include display(flex);
    @include justify-content(space-between);
```

**Comment by mgdhs** [comment]
This broke IE9, since it [doesn't support flexbox](http://caniuse.com/#feat=flexbox).

screen shot 2017-02-08 at 12 45 42

Edit: Not that it was much better before

screen shot 2017-02-08 at 12 48 00

**Comment by mgdhs** [comment]
@Feng-Shui we could merge it and have a separate issue to resolve the IE9 bugs. There is one unrelated to this PR for search and there may be more.

**Comment by Feng-Shui** [comment]
I love IE... 

Do you want to test it with:

```
 @include display(flex);
@include justify-content(space-between);
```

Instead of the manual flexbox rules that I put in?  Those mixens may have IE9 support... but I haven't looked.

**Comment by mgdhs** [comment]
@Feng-Shui see my edit, it was broken even without your changes.

I've created https://github.com/govCMS/ui-kit-base-theme/issues/71

**Pull request merged**
