### PR TITLE
get contextual links to work with UI Toolkit

### PR DESCRIPTION
**Pull request by DJMyles**
See issue https://github.com/govCMS/ui-kit-base-theme/issues/27

This will need a fair bit of testing because the way the tookit overrides stuff is a real pain as it uses a fair bit of `.js` to target elements and does funky stuff with `overflow: hidden`

### CODE REVIEW

**Comment by mgdhs** [comment]
@DJMyles can the image be referenced as `/modules/contextual/images/gear-select.png` instead of including it ours? No point duplicating something that comes with the module. I don't know if that path is always correct though (seems to be OK on govCMS).

**Comment by DJMyles** [comment]
@mgdhs it probably can however I was concerned with folder access issues which is why I moved it into the theme. I'll change it back if that's what we want.

**Comment by rujiali** [comment]
Thanks @DJMyles . It seems the context links in the head have a different style as the links in the main and footer. Please check the attached screenshot. 
screen shot 2016-12-21 at 8 40 49 am
Is it just me ?

**Comment by DJMyles** [comment]
@rujiali yep you're right, the nav styles in the header are overriding the contextual links one. I'll make a few more changes. Very tricky one to get right.

**Comment by DJMyles** [comment]
Final commit

**Pull request merged**
