### PR TITLE
[sidebar-setting] 

### PR DESCRIPTION
**Pull request by rujiali**
1. Added sidebar settings to theme setting form
2. Moved hero region out of main content area.

**To test:**

1. Clear the cache
2. Visit admin/appearance/settings/uikit_base
3. Select the 'Sidebar position' from the 'UI KIT settings section'
4. Visit general page with the uikit_base theme switched on 
5. Check the sidebar position

### CODE REVIEW

**Comment by Feng-Shui** [comment]
This looks good 👍 

Few questions and suggestions:

**`uikit_base_preprocess_page()`**

We can prob make this 4 lines

```php
// Determine the side bar class based on theme settings
$variables['sidebar_position_class'] = '';
if (theme_get_setting('sidebar_position') == 'left') {
  $variables['sidebar_position_class'] = 'sidebar-has-controls';
}
```

**Rendering to check content**

There's a few places where render array are rendered to see if they have content in them.  Rather than having these throughout the document, can we group them at the top of the file below the docblock so they're out of the way?  If we do that they don't interrupt the flow of the file as much.

**Label and descriptive text for sidebar position**

I'm going to talk to our UX designer about best practice in terms of form labels and descriptive text, so we have a consistent approach.  I might suggest some changes :)

**Comment by rujiali** [comment]
Agreed, made the changes. Will wait for your UX suggestion on the label and desc. @Feng-Shui

**Comment by Feng-Shui** [comment]
Form setting description: `A single sidebar is available, it can be positioned to the left or right of the content area.`

You ok with that?

**Comment by rujiali** [comment]
Happy. Updated the desc.

**Comment by rujiali** [comment]
Thanks, forgot that line.

**Pull request merged**
