### PR TITLE
Navigation related tweaks

### LINKED ISSUE #19: UI Kit: Navigation
**As a user
I want various levels of navigation
So I can understand where I am, where I have been and I they can go.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html

---

# Menus

## Global and Site navigation

The UI Kit's [Global navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-01-global-navigation) is described as providing ` an additional navigation level above the site navigation.`

The Kit's [Site navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-02-site-navigation) is describe as providing `site navigation to help the user to navigate between main sections.`  It sounds like Drupal's `Main menu` is in rough alignment with the purpose of the `Site navigation`.

## Local navigation

The Kit's [Local navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-03-local-navigation) is described as providing `local navigation to help the user to navigate within the current section.`.

## How this would relate to Drupal

It seems to me that the way to implement `Site navigation` and `Local navigation` in Drupal would to be a single menu that covered the whole site.  Show the top level as the `Site navigation`, and then use the `Menu block` module to show the children of the active `Site navigation` item in a block as `Local navigation`.  Another approach would be multiple menus, but the result would be the same.

## govCMS implementation

govCMS ships with a `Main menu` that only contains 1 level, and then uses Superfish to provide drop downs if that menu grows.   It also implements a menu block showing levels 2 & 3 of the `Main menu` as per the above proposed implementation (this block is placed in the sidebar).

## Propose implementation

Suggest that we

1. Assume that `Site navigation` is the top level of Drupal's `Main menu`
1. Assume that `Local navigation` will be provided using the `Menu block` module, but NOT assume that it would be a single block showing child links of the `Main menu`.
1. Given the above, we style any `Menu block` in a sidebar as `Local navigation` menu. `Or, do we style ANY Menu block as a Local navigation menu?`

I'm not sure what we do with `Global navigation` as I don't see a use for it in our site at the moment - @DJMyles with the exception of our top level audience links (Business, Corporate etc). Thoughts on this level of nav anyone?

# Content links

UI Kit refers to the functionality provided by [TOC filter](https://www.drupal.org/project/toc_filter) as [Content links](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-04-contents-links).  We should be able to implement `theme_toc_filter()` to match the Kits markup.  If this means that we aren't using any of the module's CSS, we should strip it.

# [Tab navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-05-accessibility)

This should just work out of the box?

# [Breadcrumbs](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-07-breadcrumbs)

@DJMyles @rujiali you guys have both worked on this, yeah?  Do we already have code to match the Kit's markup?

# [Skip links](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-10-skip-links)

Drupal already has a `Skip to content` link, but does not have a `Skip to section navigation` as per the Kit.  We need to:

1. See if we can get the second skip to nav link in
1. Update the styling of the links

### PR DESCRIPTION
**Pull request by Feng-Shui**
PR included a heap of small tweaks and fixes for the various navigation patterns across the site.  This PR will close #19.

### CODE REVIEW

**Comment by DJMyles** [comment]
@Feng-Shui as per discussion, "main menu" block doesn't seem to get the style whereas "main menu (expanded) block does.

**Comment by Feng-Shui** [comment]
@DJMyles this does work, but for some reason the theme cache is not picking up the new template.  Can you please try this branch again, clear cache etc (`drush cc all` and `drush cc theme-registry`).  If that doesn't work, enable devel_themer, that seemed to get the template to load for me.  Let me know if that works.

**Comment by DJMyles** [comment]
@Feng-Shui happy with this. All menus worked except main menu. I did try clearing the cache (cc all and theme-registry) but main menu still didn't render (expanded did). I didn't bother enabling devel themer to see if that worked as public (unauthenticated) users don't have exposure to that module so IMO it shouldn't form part of the QA. That being said, if you are confident that particular menu will have correct styling then all good :)

**Comment by Feng-Shui** [comment]
@DJMyles enabling that module was more to do with flushing theme caches a different way - it seemed to work for me, haven't figured that out yet.  Wasn't suggesting that the module is on to get the styling to work :D

Regardless, I'll resolve the conflicts and take another look at this one today.

**Comment by Feng-Shui** [comment]
@DJMyles I put all of the menu block in the menu and found the issue you were referring to.  I've pushed a fix for this, should be good to go now! Re-test plox!

**Comment by DJMyles** [comment]
@Feng-Shui yep perfect, all menus working now!!

**Pull request merged**
